mergestat/mergestat

- Dockerfile.init
- README.md
- docker-compose.yaml
- scripts/docker-init-entrypoint.sh
- scripts/grafana/dashboards/example.json
- scripts/grafana/grafana.ini
- scripts/grafana/provisioning/dashboards/dashboards.yaml
- scripts/grafana/provisioning/datasources/postgres.yaml
An init container has been added to docker-compose.yml
to simplify initial configuration. Migration, Seeds and Metadata.
Additionally, the init container has a helper script to simplify
adding a new repo for quicker testing.
If the first argument is `add-repo` the provided repo will be
inserted and the appropriate sync types will be added.
A default grafana setup has been included as well with a simple
example dashboard with a default postgres datasource.
> add helpers to get started with fuse faster

- internal/db/models.go
- internal/db/queries.sql
- internal/db/queries.sql.go
- internal/syncer/handlers.go
- internal/syncer/syncer.go
- migrations/default/1648216846523_alter_table_mergestat_repo_sync_queue_add_column_last_keep_alive/down.sql
- migrations/default/1648216846523_alter_table_mergestat_repo_sync_queue_add_column_last_keep_alive/up.sql
- schema.sql
- sqlc.yaml
- new column in `repo_sync_queue` table to track when the worker last "sent" a keepalive
- update worker to set the `last_keep_alive` column on an interval while a job is processing
Related to #11. This way we can have some sense of whether a job is still running or not (if the `last_keep_alive` was longer than some time ago - say 10 min - we can assume the job has timed out)
> feat: add basic keep alive behavior

- cmd/worker/main.go
- internal/db/queries.sql
- internal/db/queries.sql.go
- internal/scheduler/scheduler.go
The scheduler will now run on some interval (10 min for now) and re-queue all syncs which are not currently running. This will need to become more robust/intelligent in the future (to support scheduled syncs based on a cron/calendar description), but for now at least avoids needing to manually requeue syncs.
> feat: update the scheduler to only requeue syncs that are not running

- internal/db/models.go
- internal/db/queries.sql
- internal/db/queries.sql.go
This should handle the case if a worker crashed before setting the first `last_keep_alive` value. Closes #26
> fix: update the `MarkSyncsAsTimedOut` query to handle `NULL` `last_keep_alive`

- Dockerfile
- internal/syncer/git_commit_stats.go
- internal/syncer/git_commits.go
seeing high memory usage that seems to be related to the `GIT_COMMITS` and `GIT_STATS` syncs, specifically `go-git`. Seeing if using `libgit2` here instead addresses that.
> feat: use `git2go` (`libgit2`) directly to retrieve commits

- Makefile
in the GitHub action. we frequently trip the default timeout on mac os builds. Hopefully this helps avoid it.
> fix: add a longer timeout to the `golanci-lint` step

- ui/src/views/repositories/components/filter-header.tsx
- ui/src/views/repositories/components/page-header.tsx
- ui/src/views/repositories/components/repositories-table/columns.tsx
- ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-status.tsx
- remove some unnecessary filter buttons
- rename `Repo` -> `Repositories`
- add "empty state" text in some spots
Address some of the items in #83
> feat: touch up some parts of the `/repos` page

- cmd/worker/main.go
The default case should be 1 worker routine for now to simplify debugging
> fix: change the default worker concurrency to 1

- ui/src/views/repository-data-details/index.tsx
- ui/src/views/repository-data-logs-details/index.tsx
- ui/src/views/repository-data/components/page-header.tsx
> fix: `Repo` -> `Repositories` in page title

- ui/src/@types.tsx
- ui/src/api-logic/mappers/repos.ts
- ui/src/views/repositories/components/repositories-table/columns.tsx
- ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-name.tsx
also update the repo list with a tooltip showing the full date.
Closes out #83
> fix: rename `lastUpdate` to `createdAt` in repo info

- migrations/20220804125402_sync_job_has_error.down.sql
- migrations/20220804125402_sync_job_has_error.up.sql
this adds a pg function that's meant to be consumed as a computed column in Graphile (https://www.graphile.org/postgraphile/computed-columns/). The function `mergestat.repo_sync_queue_has_error` (which should appear in the GraphQL query just as `hasError`) looks up whether a repo sync job has an error log, and returns a boolean `true` or `false.
Closes #96
Try this query as an example:
```graphql
{
repos {
nodes {
repoSyncs {
nodes {
repoSyncQueues {
nodes {
id
status
hasError,
repoSyncLogs {
nodes {
logType
message
}
}
}
}
}
}
}
}
}
```
> feat: add pg function for detecting errors in a sync job

- ui/src/views/repositories/components/page-header.tsx
- ui/src/views/repository-data-details/index.tsx
- ui/src/views/repository-data-logs-details/index.tsx
- ui/src/views/repository-data/components/page-header.tsx
`Repositories` is too long for the sidebar nav, and we use `/repos` as the route, so let's standardize our page titles/breadcrumbs on `Repos` for now.
> fix: standardize on `Repos` for now for consistency

- cmd/worker/main.go
- internal/syncer/git_commit_stats.go
- internal/syncer/git_commits.go
- internal/syncer/git_files.go
- internal/syncer/github_pr_commits.go
- internal/syncer/github_pr_reviews.go
- internal/syncer/github_repo_issues.go
- internal/syncer/github_repo_prs.go
- internal/syncer/github_repo_stars.go
- internal/syncer/syncer.go
in these syncers, a pg transaction is kept open while the data collection occurs (fetching from the GitHub API), leading to a long-open tx, which may be leading to blocking behavior elsewhere (in general, not great to have a long open tx if we can avoid it - which we can).
> fix: address long open tx in certain syncers

- .github/workflows/publish-graphql-docker.yaml
- .github/workflows/publish-ui-docker.yaml
- .github/workflows/publish-worker-docker.yaml
This sets up GitHub Actions workflows for the two other containers defined in this repository, one for the Graphile GraphQL API and one for the Next.js UI.
Publishing these to Docker (as public images) will allow us to add them to our `helm-charts` (and allow anyone to run them as containers).
> Setup Docker build + publish workflows for `ui` and `graphql`

- internal/syncer/git_commit_stats.go
that flipped additions and deletions by comparing trees in the wrong order - thanks @amenowanna for finding this!
> fix: bug in `GIT_COMMIT_STATS` syncer

- docker-compose.yaml
so that the UI knows where to retrieve the GraphQL API in basic local startup.
Makes `docker-compose up` work locally.
> fix: updates the `docker-compose.yaml` with `POSTGRAPHILE_API`

- ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-name.tsx
Go to github repository when `github` icon is clicked. (Resolves #102)
> feat(github-icon): Adding link to github repository

- .github/workflows/ci-frontend.yaml
- .github/workflows/ci-worker.yaml
This reduces the number of CI runs on commits/PRs by removing the `macos` builds - which aren't really necessary. The vast majority of deployments here should be via a container on a linux server.
Closes #140
> chore: remove`macos` CI

- docker-compose.ui-dev.yaml
- docker-compose.yaml
- graphql/Dockerfile
- graphql/service-credentials/index.js
- graphql/service-credentials/index.ts
- graphql/service-credentials/package-lock.json
- graphql/service-credentials/package.json
- graphql/service-credentials/tsconfig.json
Implements a Graphile `makeExtendSchemaPlugin` that adds a mutation called `replaceGitHubPAT` which will allow us to set a GitHub PAT auth method from the UI. Authentication will need to be handled here eventually as well.
Closes #159
> feat: add `replaceGitHubPAT` mutation to GraphQL API

- Dockerfile
- internal/syncer/syncer.go
- internal/syncer/trivy_repo_scan.go
- migrations/20220902164407_trivy_scan_sync_type.down.sql
- migrations/20220902164407_trivy_scan_sync_type.up.sql
Sync type that runs `trivy repo ... -f json` and stashes the JSON output in the DB. Also includes a view to help extract common fields from the resulting JSON.
In general this is not a scalable way for us to continue adding sync types. However, for our current purposes this is sufficient to demonstrate the _types_ of syncs we want to continue building support for. We will soon need a better architecture and pattern for supporting arbitrary "3rd party" data sources such as `trivy` in a scalable and flexible way. That design is ongoing.
> feat: implement a `TRIVY_REPO_SCAN` sync type

- internal/syncer/trivy_repo_scan.go
if there's an exit error when running trivy, report what was on `stderr` to the log output
> chore: add a log line to the trivy scans, if there's an error

- .github/workflows/publish-graphql-docker.yaml
- .github/workflows/publish-ui-docker.yaml
- .github/workflows/publish-worker-docker.yaml
This uses cosign to sign the graphql, UI and worker images. Cosign is
configured to use keyless signing and will use a GitHub OIDC token
provided to the workflow in order to request a certificate and do the
signature.
Signatures are posted to a public transparency log (rekor.sigstore.dev)
and the signature itself is pushed to the same repository as the images
themselves.
To verify, do:
COSIGN_EXPERIMENTAL=1 cosign verify <image name>
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>
> Sign all container images with sigstore's cosign

- cmd/worker/main.go
- docker-compose.yaml
- internal/repos/importer.go
Some minor changes I made when taking a look running things locally. adds support for `DEBUG=1` for cleaner local log output (including enabling the `Debug` log level)
> some small `worker` tweaks

- internal/syncer/trivy_repo_scan.go
Closes #233 (assuming this timeout is long enough...)
> fix: add `--timeout 30m` flag to the `trivy` scan

- ui/package-lock.json
- ui/package.json
updates `eslint-config-next` and seems to address the lint config issue?
> fix: `npm i --save-dev eslint-config-next`

- ui/package-lock.json
- ui/package.json
- ui/src/@types.tsx
- ui/src/__mocks__/constants.mock.ts
- ui/src/__mocks__/syncs.mock.ts
- ui/src/__tests__/syncs.test.tsx
- ui/src/api-logic/graphql/generated/schema.ts
- ui/src/api-logic/graphql/mutations/syncs.ts
- ui/src/api-logic/graphql/queries/get-repo-syncs.query.ts
- ui/src/api-logic/mappers/repo-syncs.ts
- ui/src/components/RepoSyncIcon.tsx
- ui/src/views/hooks/useSyncNow.ts
- ui/src/views/repository-data/components/sync-types-table/components/repository-data.tsx
- ui/src/views/repository-data/components/sync-types-table/components/repository-sync-now.tsx
- ui/src/views/repository-data/components/sync-types-table/index.tsx
- ui/src/views/repository-data/index.tsx
Listing all available sync types for any repo. (Resolves #163)
- Adding new mutation to record a new `sync type` for a repo
- Showing `short name` in sync types
- Disabling going to `/repos/${repository}/${syncTypeId}` when it is first time to sync
- Unit testing
> feat(list-all-syncs): Listing all available sync types for any repo

- ui/src/@types.tsx
- ui/src/__mocks__/imports.mock.ts
- ui/src/__mocks__/repos.mock.ts
- ui/src/__mocks__/syncs.mock.ts
- ui/src/__tests__/repos.test.tsx
- ui/src/__tests__/syncs.test.tsx
- ui/src/api-logic/graphql/generated/schema.ts
- ui/src/api-logic/graphql/mutations/remove-repo.ts
- ui/src/api-logic/graphql/queries/get-repo-syncs.query.ts
- ui/src/api-logic/graphql/queries/get-repos.query.ts
- ui/src/api-logic/mappers/repo-syncs.ts
- ui/src/pages/repos/[repository]/index.tsx
- ui/src/state/contexts/repositories.context.tsx
- ui/src/utils/constants.ts
- ui/src/views/hooks/useRepoImports.ts
- ui/src/views/hooks/useRepos.ts
- ui/src/views/hooks/useSyncs.ts
- ui/src/views/repositories/components/empty-repository-table.tsx
- ui/src/views/repositories/components/empty-repository.tsx
- ui/src/views/repositories/components/page-header.tsx
- ui/src/views/repositories/components/repositories-table/index.tsx
- ui/src/views/repositories/drop-downs/repo-additional-actions-drop-down.tsx
- ui/src/views/repositories/index.tsx
- ui/src/views/repositories/modals/auto-import-repository-modals/manage-auto-imports-modal.tsx
- ui/src/views/repositories/modals/remove-repository-modal/index.tsx
- ui/src/views/repository-data/index.tsx
Implementing functionality to remove a repo. (Resolves #101)
- Show card `Start by adding a GitHub authentication token` when there's no repos.
- It was creating several queries with polling interval. This bug was fixed.
- No Unit testing included. I will include the unit testing in next issue which has an easier `button` element to grab.
> feat(remove-repo): Implementing functionality to remove a repo

- Dockerfile
- go.mod
- go.sum
- internal/syncer/git_blame.go
- internal/syncer/git_commit_stats.go
- internal/syncer/git_commits.go
- internal/syncer/git_files.go
- internal/syncer/git_refs.go
- internal/syncer/syncer.go
- migrations/20220911143334_git_blame_sync.down.sql
- migrations/20220911143334_git_blame_sync.up.sql
- Implement a `GIT_BLAME` sync that inserts a row for every line of code (!) in a repo, including it's basic blame info. This approach shells out to the `git` CLI, which is much more performant than an implementation using `libgit2` (in our initial tests)
- Some minor updates in other syncers to remove use of deprecated funcs
Addresses #151
> feat: implement basic `GIT_BLAME` syncer

- .github/workflows/publish-graphql-docker.yaml
- .github/workflows/publish-ui-docker.yaml
- .github/workflows/publish-worker-docker.yaml
this should address the failing `cosign` run
> fix: reference to `meta` step in GitHub workflow

- ui/src/components/RepoSyncIcon.tsx
- ui/src/views/repository-data/components/sync-types-table/index.tsx
Adding tooltips to status icons. (Resolves #116)
> feat(tooltip-status): Adding tooltips to status icons

- docker-compose.ui-dev.yaml
- docker-compose.yaml
- graphql/service-credentials/index.js
- graphql/service-credentials/index.ts
set's up a new graphql query `databaseConnection` which returns the contents of the following ENV vars (if they are set):
- `DISPLAY_PG_HOSTNAME`
- `DISPLAY_PG_PORT`
- `DISPLAY_PG_DATABASE`
- `DISPLAY_PG_USER`
**Note** password is intentionally left out here since it's a secret. We'll omit that from the UI and maybe add a note saying users should get a password from their admin.
So that the UI can display them on the `/connect` page. The intent is that an operator will set these values ahead of time if they want to expose a DB connection string/params in the UI for easy use.
Next will be to implement the UI to use this `query`.
Closes #95
> feat: implement simple way to show DB creds (from ENV)

- migrations/20220920081312_add_indexing.up.sql
This PR is to cover the known slow queries that we have we will need to add indexes for all of the foreign keys to complete our indexing first pass.
> feat: adding indexing to cover slow queries

- migrations/20220925185637_current_user_func.up.sql
This can now be accessed by PostGraphile so the UI can call `currentMergeStatuser` to retrieve the DB username of the currently authenticated user.
Closes #320
> feat: add `current_merge_stat_user` func to db

- migrations/20220511014018_init.up.sql
- migrations/20220928141712_schema_migrations_history.up.sql
Adding a Table, Function, and Trigger to track the history of our schema migrations. Currently the `schema_migrations` table only stores the latest migration so it is difficult to track what migrations were applied and when and this is an issue when troubleshooting failed or missed migrations.
The solution was found in an [issue](https://github.com/golang-migrate/migrate/issues/179#issuecomment-479740765) for our migration tool
Resolves #330 
Example output of the table on a clean database where all migrations ran
> feat: adding schema migrations history table

- ui/src/views/repository-data-details/components/repo-data-type-logs/logs-table/index.tsx
- ui/src/views/repository-data-logs-details/index.tsx
Some small suggestions for the styling of the empty state of the logs:
- smaller text size
- Added empty state panel
> Small tweaks log entries empty

- internal/syncer/git_blame.go
- internal/syncer/git_commit_stats.go
- internal/syncer/git_commits.go
- internal/syncer/git_files.go
- internal/syncer/git_refs.go
- internal/syncer/github_pr_commits.go
- internal/syncer/github_pr_reviews.go
- internal/syncer/github_repo_issues.go
- internal/syncer/github_repo_prs.go
- internal/syncer/github_repo_stars.go
- internal/syncer/handlers.go
- internal/syncer/syncer.go
- internal/syncer/trivy_repo_scan.go
This adds more sync log insertions to the course of every sync job we have defined. It closes #232, but doesn't address _all_ of the bullets/suggestions in the ticket. This PR:
This _does not_ add log entries for every API request made to GitHub. This is because these are done via https://github.com/mergestat/mergestat and so we have a harder time accessing those events in the sync run flow.
This should be sufficient IMO to close out #232 for this first version.
> More verbose sync logs

- Dockerfile
- internal/syncer/syft_repo_scan.go
- internal/syncer/syncer.go
- migrations/20221002201938_syft_sync_support.up.sql
This PR should be merged _after_ #346.
`syft` (https://github.com/anchore/syft) is a CLI that generates SBOMs from various sources, including filesystems. This sync type implements a basic sync that uploads the results of `syft . -o json` on a git repo into the DB.
A view is also included with some simple JSON parsing to extract the `artifacts` list from the `syft` output JSON, for easier querying.
See here: https://github.com/anchore/syft for more context.
> feat: implement `SYFT_REPO_SCAN` sync type

- internal/syncer/syncer.go
causing some weird issues with "double" log messages appearing
> fix: create a copy of the logger, instead of re-using

- ui/src/api-logic/graphql/generated/schema.ts
- ui/src/api-logic/graphql/queries/get-repos.query.ts
- ui/src/api-logic/graphql/queries/get-sync-history-logs.query.ts
- ui/src/api-logic/mappers/repos.ts
- ui/src/api-logic/mappers/syncs-logs.ts
Previously we were using the `type` column of repo sync types (`GIT_COMMIT`, `GITHUB_REPO_PRS`, etc) to display repo sync type _names_ in some spots of the UI. Now that we track a human readable name in the `short_name` column, we should use that instead. This updates the UI to use that column in:
Closes #223
> Use sync type short name instead of the `type` enum

- ui/package-lock.json
- ui/package.json
- ui/src/views/repositories/index.tsx
the message that's displayed when a repo auto import is running for the first time.
Closes #345
> feat: add a spinner to the auto import alert

- cmd/worker/main.go
We encountered this in a deployment, where the `CONCURRENCY` env could not be parsed, and so the `concurrency` _var_ in this part of the code got _set to `0`_, which is unexpected behavior. It should respect the default value (current `1`).
This should address that.
> fix: subtle bug when `CONCURRENCY` env can't be parsed

- ui/src/views/repository-data/components/sync-types-table/components/repository-sync-status.tsx
I think we should address the bugginess in it before turning it back on. I'd like to use a library for this, something like this: https://popper.js.org/react-popper/v2/
> fix: commenting out the sync status bar tooltip for now

- README.md
Now that the rename is done, begin replacing references to `fuse`.
> chore: update some references to `fuse` in the `README`

- README.md
Fixes a copy + paste typo in the README
> fix: typo in GitHub actions badge

- ui/src/pages/settings/repo-auto-imports/[importId].tsx
The thumbnail size was inconsistent with the other breadcrumbs and there was a duplicate ColoredBox wrapper
> Update breadcrumb thumbnail size

- ui/src/views/repository-data-details/components/repo-data-type-logs/index.tsx
The learn more link didn't open in a new tab
> fix: add target blank to learn more link

- docker-compose.yaml
For now, just use inline env vars in the `docker-compose.yaml` file. We can configure a `make` target for a more complex setup that uses `.env-worker` later if we need it.
This allows the app to be brought up on a "fresh" clone of the repo with just `docker-compose up`. Closes #418
> fix: remove `.env-worker` requirement for `docker-compose`

- ui/src/views/settings/repo-auto-imports/index.tsx
There was a small bug: the auto import settings overview was not scrollable yet causing the toolbar to shrink when there are many items. This should be fixed by this PR:
> fix: fix scroll bug settings

- ui/src/pages/api/admin-auth.ts
to allow for passwords (and usernames) with special characters. Closes #426
> feat: call `encodeURI` when validating pg credentials

- migrations/900000000000001_readaccess_defaults.up.sql
Added defaults for readaccess select privileges. Changed the migrations numbers to be a sequence instead of date driven to address bad name given on previous migration as well as to force us to use a sequence and enforce merging of migrations when there is a conflict.
Tested by creating a new table in public schema and being able to still select it from the Queries section in the UI.
resolves #428
> fix: set readaccess defaults 

- cmd/worker/main.go
- docker-compose.yaml
changes the `DEBUG` env var into `LOG_LEVEL` which would allow an operator to set the minimum log level they want to see structured logs for (defaults to `info`).
Also adds the `PRETTY_LOGS` env var (if set to `1`) to enable console friendly (more human readable) log output.
> feat: refine how we handle setting log level in the worker

- migrations/20220511014018_init.up.sql
to make part of it idempotent (see if it addresses the error we see when running migrations using a different default pg user)
> fix: try back modifying the initial migration

- .github/workflows/lint_sql.yml
- migrations/20220511014018_init.up.sql
fixing this errors on main 
`(details: pq: relation "schema_migrations" already exists) error="migration failed: relation \"schema_migrations\" already exists in line 0`
> fix(migrations):create schema migration only if not exits

- .github/workflows/lint_sql.yml
- Makefile
- docker-compose.dev.yaml
- docker-compose.yaml
we were seeing problems when running `docker-compose up`, in particular the `graphql` service would start before the migrations in the `worker` service were complete. This would lead to an invalid GraphQL API schema being served (no entities) and errors displaying in the UI. Not a great UX. The solution was to just rerun `docker-compose up` and hope the timing issue didn't occur again.
This addresses that (it should anyways) by adding health checks to some services and `condition: service_healthy` in the `depends_on` config in some spots.
Note it also brings back the `DEBUG=1` env var, which is what enables the `/metrics` endpoint in the `worker`, which is what we're using a healthcheck now - this is probably worth improving.
- use pinned, pre-built images from docker hub
- bumps the …
> fix: update the `docker-compose` file to address startup timing issues

- ui/src/pages/settings/index.tsx
- ui/src/utils/constants.ts
to point specifically to the instructions for "classic" PATs which are what we currently support (fine-grained we don't yet support).
> chore: update the link to the GitHub docs on PATs

- internal/warehouse/github_actions.go
this err value was causing the break the proccess on first error  .
With this a experimental change because now we don't check for errors removing the donwloaded   files we only log them .
A better approach should be implemented
> fix(warehouse): Making changes to the default return value getting  the logs

- internal/syncer/syft_repo_scan.go
this  param was hardcoded to the env variable string not the value
> fix(syncers):Adding os.getenv to tmp dir param

- ui/src/views/repository-data/components/sync-types-table/components/repository-table-row-options.tsx
Adding coming soon tooltip. (Resolves #477)
> chore(syncs): Adding coming soon tooltip

- .sqlfluff
- internal/db/models.go
- internal/db/queries.sql
- internal/db/queries.sql.go
- migrations/900000000000003_add_set_sync_job_status.up.sql
- ui/src/api-logic/graphql/queries/get-repos.query.ts
Changing logic to store the queue id for the last completion of each repo sync. This will allow us to check for errors with in the sync runs without having to rank all of the jobs in the queue which is a very expensive query. I tested with several different indexing changes but our current indexing continued to be chosen by the database engine. The most expensive part of this query is still having to check the queue to not query syncs that are currently `QUEUED` or `RUNNING`.
Resolves #483
> feat: last error query performance enhancements

- go.mod
- go.sum
- internal/syncer/git_blame.go
or at least try to by increasing the size of the buffer used in the `git blame` parser. Also begins reporting the file path in the error log to help with troubleshooting.
Closes #513
> fix: address `token too long` error

- ui/src/views/repository-data/components/sync-types-table/components/repository-sync-now.tsx
- ui/src/views/repository-data/components/sync-types-table/index.tsx
Adding feedback actions for the user. (Resolves #473)
Fixed:
- Adding fast feedback when sync button is pressed (leaving it in queued state)
- Showing an alert when schedule toggle is switched. (Sync On/Sync Off)
Couldn't reproduce them:
- Blue banner with the spinner is being showed immediately.
- Auto import list in settings is being showed well if a new import is added. For this one I remember I did a fix.
> chore(loaders): Adding feedback actions for the user

- graphql/exec-sql/index.js
- graphql/exec-sql/index.ts
This will allow both readonly and non-readonly queries to be run in the UI, based on what the API request sends. This is distinct from user permissions, and is meant more to be a "break glass" type of param to protect users running queries by defaulting to readonly (and explicitly requiring them to opt-in to non-readonly query access).
> feat: add a `disableReadOnly` flag to the `execSQL` graphql query

- internal/syncer/git_blame.go
Also add additional fields as context to make for easier debugging. Test this against `https://github.com/hashicorp/nomad` which had some trouble with a file:
```
error blaming file: website/public/img/home-hero-pattern.svg in repo: /tmp/mergestat-repo-1952571063, bufio.Scanner: token too long error="bufio.Scanner: token too long" filePath=website/public/img/home-hero-pattern.svg repo=https://github.com/hashicorp/nomad
```
This makes it such that errors that do not "halt" the sync process are now warnings (so that alerting doesn't pick them up)
> chore: change some error logging to warnings in the `GIT_BLAME` syncer

- internal/helper/helper.go
- internal/warehouse/github_actions_test.go
- Some renaming in the tests for clarity
- Simplify the `GetRepoOwnerAndRepoName` helper to be a bit more generic
> Small tweaks to the GitHub Actions test setup

- ui/src/pages/api/admin-auth.ts
in the login API. There are 11 characters (according to this page: https://thisthat.dev/encode-uri-vs-encode-uri-component/) not encoded by `encodeURIComponent` which may appear in PG passwords, causing issues logging in for users with those in their password.
This should address that, closes #453
> fix: use `encodeURIComponent` instead of `encodeURI`

- docker-compose.yaml
In preparation for a new release
> chore: bump `docker-compose` to `1.4.0-beta`

- internal/syncer/git_blame.go
- internal/syncer/git_commit_stats.go
- internal/syncer/git_commits.go
- internal/syncer/git_files.go
- internal/syncer/git_refs.go
- internal/syncer/github_actions.go
- internal/syncer/github_pr_commits.go
- internal/syncer/github_pr_reviews.go
- internal/syncer/github_repo_issues.go
- internal/syncer/github_repo_metadata.go
- internal/syncer/github_repo_prs.go
- internal/syncer/github_repo_stars.go
- internal/syncer/handlers.go
- internal/syncer/syft_repo_scan.go
- internal/syncer/trivy_repo_scan.go
Instead of a "catch all" function, use constant value format strings. Slightly more verbose, but I think helps clarify what the resulting log line will look like.
> feat: refactor how some of the DB logging formatting works

- ui/src/views/repositories/components/repositories-table/index.tsx
> chore: make `Set up sync types` a clickable link

- ui/src/pages/api/admin-auth.ts
Errors encountered from auth failure should now just be warnings (vs errors on stdout) and should be structured (JSON format)
> fix: log as JSON in the `/api/admin-auth` endpoint

- examples/git/docker-images/sql/docker-base-image-versions.sql
- examples/git/go/env-vars/sql/go-env-vars.sql
- examples/github/repos/sql/repo-counts-by-language.sql
- examples/github/repos/sql/repo-counts-by-license.sql
Adds some more example queries to the `examples/` directory:
- Docker image version querying
- Go ENV var code search
- Repo counts by language
- Repo counts by license
> docs: add some additional SQL examples

- migrations/900000000000011_last_repo_sync_queue_fk_null.up.sql
- ui/src/__mocks__/repos.mock.ts
- ui/src/api-logic/graphql/generated/schema.ts
- ui/src/api-logic/graphql/queries/get-repos.query.ts
- ui/src/api-logic/mappers/repos.ts
Make use of the `last_completed_repo_sync_queue_id` column we now have in the `mergestat.repo_syncs` table. This ends up being more performant. Also removes the `hasError` function call
> feat: tweak the graphql query used by `getRepos(...)`

- migrations/900000000000011_last_repo_sync_queue_fk_null.up.sql
This fixes the issue with migration 11 where the constraint fails to be added when there are orphaned id's in the new FK constraint. To address this we have added a query to clean these records up before adding the constraint and additionally have added the command to set the id's to null when the parent record is deleted. Also added support for resetting dirty migrations automatically so we can recover broken migrations without manual intervention.
resolves #628
> fix: migration 11

- ui/package.json
In an effort to get renovate to use `node` 16 when installing dependencies
> chore: try add ing `"node": "^16"` to `engines` block of `package.json`

- ui/src/views/repositories/index.tsx
Adds comma formatting to the metric numbers
> feat: use `Intl.NumberFormat()` in our `/repos` metrics number

- Dockerfile
- internal/syncer/gitleaks_repo_scan.go
- internal/syncer/syncer.go
- migrations/900000000000012_add_gitleaks_sync.up.sql
Another POC syncer that brings in this tool: https://gitleaks.io/ as a sync type. Runs a scan on a repo and then stores the JSON output in the DB. Also sets up a view to make the JSON data a bit easier to consume.
> feat: implement a `gitleaks` syncer for detecting secrets in a repo

- docker-compose.yaml
In preparation for `v1.6.0-beta` release
> chore: bump version to `v1.6.0-beta`

- internal/syncer/syncer.go
When testing out support for local or `file://` URLs (see #635), I ran into this issue where the GitHub token was being appended (and the path was being escaped / encoded), even for local filesystem paths.
> fix(syncer): do not append token to local URLs

- Dockerfile
- internal/syncer/syncer.go
- internal/syncer/yelp_detect_secrets_repo_scan.go
- migrations/900000000000013_add_yelp_detect_secrets_sync.up.sql
Similar to Gitleaks, but using this tool instead: https://github.com/Yelp/detect-secrets.
Closes #639
> feat: implement `Yelp/detect-secrets` as another *experimental* repo scan type

- migrations/900000000000016_update_users_view_only_mergestat_roles.up.sql
to exclude DB users that are *not* in one of the pre-set mergestat roles: `'mergestat_role_admin', 'mergestat_role_user', 'mergestat_role_readonly'`
Should be a backend solution that closes #605
> feat: updates the `mergestat.user_mgmt_pg_users` view

- migrations/900000000000016_update_users_view_only_mergestat_roles.up.sql
Addresses an issue in the latest migration:
Validated the fix locally
> fix: typo (extra `;`) in latest migration

- migrations/900000000000017_add_table_comments.up.sql
this will be useful for introspection and surfacing docs in our app
> fix: add comments for tables/columns/views for `GITLEAKS_REPO_SCAN` and `YELP_DETECT_SECRETS_REPO_SCAN`

- ui/src/pages/connect/index.tsx
- ui/src/pages/login/index.tsx
- ui/src/pages/queries/index.tsx
- ui/src/pages/repos/[repository]/[syncTypeId]/[logID].tsx
- ui/src/pages/repos/index.tsx
- ui/src/pages/settings/index.tsx
- ui/src/pages/settings/repo-auto-imports/[importId].tsx
- ui/src/pages/settings/repo-auto-imports/index.tsx
- ui/src/pages/settings/user-management/index.tsx
- ui/src/pages/settings/user-settings/index.tsx
- ui/src/utils/constants.ts
- ui/src/views/hooks/useSyncs.ts
- ui/src/views/hooks/useSyncsLogs.ts
- ui/src/views/settings/repo-auto-imports/index.tsx
- ui/src/views/settings/user-management/index.tsx
- ui/src/views/settings/user-settings/index.tsx
- I went for `-` as a separator instead of `|` as it seems more widely used and feels a bit more readable
- Ordered titles from detail to top level, for example `Sync 22 Dec 2022 - 17:38 - Git Blame - mergestat/workspace - Repos - MergeStat` 
Resolves #606
> fix: fix page titles

- docker-compose.yaml
Prep for `v1.8.0-beta` release
> chore: bump to `v1.8.0-beta` in `docker-compose.yaml`

- docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.8.0-beta...main
> chore: bump version to `v1.8.1-beta`

- docker-compose.yaml
- ui/src/pages/api/admin-auth.ts
This allows an operator to use non ssl-only cookies for user sessions of the web app. This can be useful in situations where MergeStat is run internally on a private IP. Otherwise, the UI requires an HTTPS connection to function.
Closes #673
Validated on an Equinix Metal server
> feat: implement support for `INSECURE_SESSION_COOKIE` env var in the UI

- docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.8.2-beta...main
> chore: bump to version `v1.9.2-beta`

- graphql/exec-sql/index.js
- graphql/exec-sql/index.ts
- migrations/900000000000019_query_history.up.sql
Adds a table to track the history of queries run in the UI, by user.
See here: https://www.postgresql.org/docs/current/ddl-rowsecurity.html for some additional context on the RLS.
Closes #722
> feat: implement first pass at backend for query history functionality

- graphql/exec-sql/index.js
- graphql/exec-sql/index.ts
this holds how long it took the query to run in ms
> feat: send back `queryRunningTimeMs` in the `execSQL` call

- Dockerfile
- internal/syncer/ossf_scorecard_scan.go
- internal/syncer/syncer.go
- migrations/900000000000021_ossf_scorecard.up.sql
more context can be found here: https://github.com/ossf/scorecard. Produces a score for a repo, stores the results as JSON in the DB, and creates some views for easier consumption of the data.
> feat: implement an additional experimental syncer, the `ossf/scorecard` project

- .github/workflows/ci-worker.yaml
- .sqlfluff
- migrations/900000000000014_add_schema_introspection_view.up.sql
- migrations/900000000000021_ossf_scorecard.up.sql
the intent is to catch migrations that break `sqlc` early on. Closes #758
> fix: run `sqlc generate` as a part of CI for the worker

- internal/syncer/github_repo_metadata.go
> fix: typos in some struct/json handling in the `GITHUB_REPO_METADATA` syncer

- docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.11.0-beta...main
> chore: bump version to `v1.12.0-beta`

- ui/jest.config.js
Hopefully this will give some breathing room to our current UI tests that are right on the cusp of the default 5000ms timeout. This won't catch all of our flaky tests, but hopefully will address the ones that are caused by timeouts. Closes #615
@german-mergestat what do you think?
> fix: bump up the default `jest` timeout in the UI tests

- docker-compose.yaml
- migrations/900000000000022_fix_gosec_table.up.sql
This resolves #772 and bumps the version to 1.13.0-beta
> Fix broken migration for gosec_repo_scans

- internal/syncer/github_actions.go
- internal/syncer/github_pr_commits.go
- internal/syncer/github_pr_reviews.go
- internal/syncer/github_repo_issues.go
- internal/syncer/github_repo_metadata.go
- internal/syncer/github_repo_prs.go
- internal/syncer/github_repo_stars.go
- internal/syncer/ossf_scorecard_scan.go
- internal/syncer/syncer.go
This resolves the issue of this syncs running indefinitely without returning any error to the user 
Syncs affected are GITHUB_ACTIONS and OSSF_SCORECARD_REPO_SCAN
Closes #776
> fix(syncer): Failing syncs when pat is not present

- internal/syncer/git_remotes.go
- internal/syncer/syncer.go
- migrations/900000000000024_git_remotes_syncer.up.sql
Retrieves the remotes of a git repo. Only relevant for local, on-disk repos. Closes [#792](https://github.com/mergestat/mergestat/compare/feat/null/issues/792).
Errors on remote repos:
Works for local file path repos:
> feat: implement `GIT_REMOTES` repo syncer

- migrations/900000000000025_grype_synced_at.up.sql
Improvement with the new column synced_at and also comments on the columns and table 
Closes #793
> chore(migrations): Adding synced_at and comments on grype table

- migrations/900000000000027_init_role_perms_fix.up.sql
By default, we often use the `mergestat_admin` user. This migration fixes an issue where that user does not have sufficient permissions to take on the `mergestat_anonymous` role, which is what PostGraphile uses by default for unauthenticated users.
> fix: add a migration to run `GRANT mergestat_anonymous TO mergestat_admin;`

- cmd/worker/main.go
moves it closer to the initialization of the `upstream` client
> chore: move `SetMaxOpenConns` call to right after `upstream` is defined

- ui/package-lock.json
- ui/package.json
- ui/src/@types.tsx
- ui/src/api-logic/graphql/generated/schema.ts
- ui/src/api-logic/graphql/mutations/saved-query.ts
- ui/src/api-logic/graphql/queries/get-saved-query.ts
- ui/src/components/Sidebar/index.tsx
- ui/src/pages/queries/saved/[savedQueryId]/index.tsx
- ui/src/pages/queries/saved/index.tsx
- ui/src/state/contexts/query.context.tsx
- ui/src/state/contexts/saved-query.context.tsx
- ui/src/utils/constants.ts
- ui/src/views/hooks/useQueryEditor.ts
- ui/src/views/hooks/useSavedQuery.ts
- ui/src/views/repositories/components/empty-repository-table.tsx
- ui/src/views/saved-queries/components/empty-saved-queries.tsx
- ui/src/views/saved-queries/components/filter-footer.tsx
- ui/src/views/saved-queries/components/filter-header.tsx
- ui/src/views/saved-queries/components/saved-queries-table.tsx
- ui/src/views/saved-queries/index.tsx
- ui/src/views/saved-queries/modals/remove-saved-query.tsx
- ui/src/views/sql-query-editor/components/sql-editor-section.tsx
- ui/src/views/sql-query-editor/components/state-filled.tsx
- ui/src/views/sql-query-editor/index.tsx
- ui/src/views/sql-query-editor/modals/query-setting.tsx
Starting implementation for `Saved Queries`. (Resolves #783)
- Implementing first approach for Saved queries.
- Fixing bug for empty repository (no showing image).
> feat(saved-queries): Starting implementation for Saved Queries

- ui/src/views/saved-queries/components/saved-queries-table.tsx
removes the `Me` string for the sake of clarity
> chore: just use `{query.createdBy}` when showing creator of saved query

- migrations/900000000000029_fk_to_orphan_tables.up.sql
Taking in consideration orphan records,  to test this code:
1. Comment the content of 29 migration and run mergestat
2. Import mergestat repos and set the next default syncs syft,grype,git_remotes,yelp and gitleaks and let them finish.
3. delete the import and check if the information of this syncs  persist, now set the schema_migrations to 028 or below and delete the schema_history until that one also.
4. uncomment the content of 029 and run make docker-build-worker
5. After a make dev  check if the tables are empty if so the migrations solves our issue
Closes #833
> fix(migrations):Deleting orphan records

- cmd/worker/main.go
- go.mod
- go.sum
- internal/db/models.go
- internal/db/querier.go
- internal/db/queries.sql
- internal/db/queries.sql.go
- internal/helper/helper.go
- internal/jobs/repo/import.go
- internal/mocks/mock_queries.go
- internal/warehouse/github_actions.go
- internal/warehouse/github_actions_test.go
- internal/warehouse/warehouse.go
- ui/src/views/hooks/useRepos.ts
We implement here a way for our import to respect concurrency requirements of github APi by making our syncs aware of a running import is it a running import the context of that sync/operation will wait until the import finishes  its process.WE ONLY DO THIS WHEN A PAT IS PROVIDED, when is not we let the syncs and imports to hit the rate limit of github.
To test this:
No Pat Scenario:
1. log without pat
2. import Google as a repo ORG,wait and see the error of rate limit displayed in the UI
PAT scenario:
1. log with pat.
2. import mergestat as a repo ORG wait for it to finish.
3. go to mergestat/mergestat and run github actions.
4. Import google, then check the logs of your docker  and wait for this logs  indicating that we are waiting for the import to finish
Test the grapql API:
1. after …
> feat(importer):Adding rate limit and handling syncs to respect imports in progress

- ui/package-lock.json
- ui/package.json
Should pull in some new updates, including the new navigation interactions
> chore: upgrade `blocks` and `icons` to latest

- ui/src/utils/constants.ts
- ui/src/views/hooks/useQueryEditor.ts
- ui/src/views/sql-query-editor/components/state-empty.tsx
- ui/src/views/sql-query-editor/components/state-rows-affected.tsx
- ui/src/views/sql-query-editor/index.tsx
So we werent checking for rows counts / rows affected  so when we did and operation with no rows returned we ommited the result and  show the empty editor when actually we had rows affected.
With this changes we take in consideration all rows and rows count/affected.
To test you need to :
1. do any operation that returns no rows and also affect rows
2. you should see the rows impacted but that query
Closes #824
> fix(editor): checking for rows affected in query editor

- internal/jobs/repo/vendor_github.go
addresses the inconsistent GitHub repo URLs. Closes #873
> fix: auto import default syncs for `GitHub`

- ui/src/components/Sidebar/index.tsx
Previously, for _subpages_ of `/repos` nothing would be highlighted in the navbar. Now, we highlight the top level (`Repos`) when we're on a page such as `/repos/0c7fa3ae-2197-4e8e-95ee-2d6dd2febe91/d3dba41f-8c98-4ca1-a516-a627a4394275` but _not_ on `/repos/repo-auto-imports`
> fix: the logic for highlighting the `Repos` top-level navbar item

- internal/syncer/git_blame.go
> fix: `ioutil.TempFile` is deprecated in favor of `os.CreateTemp`

- ui/src/components/Sidebar/index.tsx
don't double highlight `Repos` and `Git Sources`
> fix: navbar highlighting for `Repos`

- ui/src/views/repo-git-sources/git-sources/components/git-sources-table.tsx
Showing description in git sources list. (Resolves #905)
> chore(git-sources-list): Showing description in git sources list

- docker-compose.yaml
skipping `1.20.0-beta` as we forgot to update the `docker-compose.yaml` file for it
> chore: bump to `1.21.0-beta`

- internal/jobs/repo/vendor_bitbucket.go
This PR fixes an issue with Bitbucket auto-imports where a `NOT NULL` columns (`repos.tags`) was being set to `NULL` in code, causing the auto-import to fail.
> FIX: Bitbucket auto-import

- internal/syncer/syncer.go
currently if the `username` column is `NULL` in the credential, git clones will fail. This should address this _at the clone_ vs having to ensure the inputs to the credentials table always have a dummy username.
> fix: git clones when `username` is `NULL` in the credential

- internal/syncer/grype_repo_scan.go
Grype scanner was failing on _second_ runs because we were reusing the same clone dir across runs. This should address that.
> fix: issue with grype scanner reusing previous tmp dir location

- internal/syncer/syncer.go
- ui/src/views/repo-git-sources/git-source-detail/components/repos/components/manual-import-table.tsx
(i.e. use a `nil` auth). Closes #925
> fix: if there's no token (during repo clone) don't supply any auth

- internal/syncer/gitleaks_repo_scan.go
- internal/syncer/grype_repo_scan.go
validated locally. see diff for summary of fixes. my guess is recent `Dockerfile` changes caused the issue with Gitleaks at least.
> fix: `grype` and `gitleaks` scanners had some perms/misconfig issues

- ui/package-lock.json
- ui/package.json
- ui/src/components/Sidebar/index.tsx
This should enable a better sidebar UX when a user is directly linked to a child page or refresh a child page.
> feat: bump `blocks` and use `defaultOpen` prop in `<Sidebar />`

- internal/syncer/grype_repo_scan.go
since we now set `cmd.Dir = tmpPath`
> fix: use the current dir when running `grype`

- internal/db/models.go
- migrations/900000000000048_container_based_sync_tweaks.up.sql
Closes #946.
Also rename the `displayname` column to `display_name` in `mergestat.container_image_types`
> fix: add a description field to the `container_images` table

- internal/jobs/sync/podman/podman.go
this should address the PG hostname resolution
> chore: use `--network host` when running container syncs

- docker-compose.ui-dev.yaml
- docker-compose.yaml
- `POSTGRES_PASSWORD`
- `JWT_SECRET`
- `ENCRYPTION_SECRET`
The can now be set as env vars when running `docker-compose up` (or `make dev`). The current "hardcoded" values will be the defaults for consistency.
This allows a user wanting to run an instance via `docker-compose` to more easily inject their own secrets via env vars.
Closes #976
> chore: allow overrides of secrets in `docker-compose` setup

- cmd/worker/main.go
- internal/cron/auto_import_schedule.go
- internal/db/models.go
- internal/db/querier.go
- internal/db/queries.sql
- internal/db/queries.sql.go
- internal/jobs/repo/import.go
- internal/jobs/repo/vendor_bitbucket.go
- internal/jobs/repo/vendor_github.go
- internal/jobs/repo/vendor_gitlab.go
- internal/mocks/mock_queries.go
This PR updates the repo auto-import process to use `{vendor}-{provider}`-specific queues to better manage concurrency and api usage. Closes mergestat/mergestat#969
> feat: use vendor+provider specific queues for repo import jobs

- docker-compose.yaml
Bump version in  `docker-compose` to `1.22.3-beta`
> chore: bump to `1.22.3-beta`

- graphql/container-sync-jobs/index.js
- graphql/container-sync-jobs/index.ts
- graphql/container-sync-jobs/package-lock.json
- graphql/container-sync-jobs/package.json
- migrations/900000000000052_add_unique_constraint_to_sync.up.sql
This PR adds a new `bulkEnableSync` to enable sync for a given container image across all repositories from a given provider. Fixes #965
> feat: add bulkEnableSync mutation

- ui/package-lock.json
- ui/package.json
- ui/src/@types.tsx
- ui/src/api-logic/graphql/generated/schema.ts
- ui/src/api-logic/graphql/queries/get-query-history.ts
- ui/src/api-logic/mappers/history.ts
- ui/src/state/contexts/query.context.tsx
- ui/src/styles/globals.css
- ui/src/views/hooks/useQueryEditor.ts
- ui/src/views/hooks/useQueryHistory.ts
- ui/src/views/sql-query-editor/index.tsx
- ui/src/views/sql-query-editor/modals/query-history.tsx
- ui/tailwind.config.js
- Added empty state
- Used `react-syntax-highlighter` instead of the Monaco editor to show the query preview
- Added `t-master-detail` styles instead of the `VerticalNav` component for the list (needs to be synced to `blocks`)
- Cleaned up `global.css` by removing duplicate styles that are already in `blocks`
A possible future improvement would be to install `@headlessui` and use the `Tabs` component (`vertical` variant) to make it keyboard accessible (use up/down arrow keys to move through the list)
> feat: Implement frontend experience for Initial Query History (with visual improvements)

- cmd/worker/main.go
- internal/jobs/sync/podman/podman.go
Implements some changes to how container-syncs are run.
- Some tweaks to the logging behavior
- Default to _not_ cloning a repo unless a container image "asks" for it, via the `com.mergestat.sync.clone` label
- Also supply params as an env (`MERGESTAT_PARAMS`)
> feat: start refactoring container-sync approach

- migrations/900000000000054_missing_pkey.sql
This one slipped thru the cracks
> fix: add a PK to `mergestat.container_sync_executions`

- internal/syncer/github_prs_and_commits.go
- internal/syncer/syncer.go
will be kept "hidden" for the time being. Retrieves GitHub PRs and their commits for a repo using the REST API.
> feat: implement `GITHUB_PRS_AND_COMMITS` syncer

- internal/syncer/github_prs_and_commits.go
addresses a bug in the `GITHUB_PRS_AND_COMMITS` sync
> fix: some incorrect values for `merged_at` and `updated_at`

- .github/workflows/publish-console-docker.yaml
- .github/workflows/publish-graphql-docker.yaml
- .github/workflows/publish-worker-docker.yaml
Adding support for multi-arch images to address issues with new container syncs. When running the amd64 image an an M1 Mac we were seeing the following errors
```
cannot clone: Invalid argument
Error: cannot re-exec process
```
When running Mergestat on an image that matches the local arch this error went away. For now we are starting with adding `arm64` on top of the `amd64` image we were generating.
> feat: adding support for multi-arch images

- graphql/exec-sql/index.js
- graphql/exec-sql/index.ts
- migrations/900000000000061_add_demo_role.up.sql
> Demo role and statement timeouts

- cmd/worker/main.go
when passing into the container sync
> fix: remove query params from pg connection string

- docker-compose.yaml
Removing links from compose file that is not needed and break support for podman-compose. Make file commands are still docker based only for now but base use case is covered now.
Resolves #1071
> feat: removing links to support podman-compose

- ui/src/styles/globals.css
- ui/src/views/explore/components/header-explore/components/filter-section/components/filter.tsx
- ui/src/views/explore/modals/data-table.tsx
- Small visual improvements to filter buttons (size, font-weight, spacing)
- Adjusted active filters, clicking an active filter still opens the filter popover, only clicking the "x" clears the filter (otherwise you have to clear the filter first to modify it)
- Made the table modal a bit bigger
> fix: small visual fixes explore ui

- ui/src/utils/index.tsx
> fix: check for PATs issued from old gitlab versions

- cmd/worker/main.go
Asked on the [slack](https://mergestatcommunity.slack.com/archives/C02KEJ5M7RA/p1696672369445719) how to configure how often jobs are scheduled, so started looking at it. 
It seems that it was already mentioned in the code, so just adding env variable with default values to make it possible to run only once a day for example (In my case we have a lot of repos, running it more often doesn't really bring value but add a lot of computing). 
I didn't configure the timeout one, but can add it if you think it's necessary
> feat: add possibility to set scheduler and syncer interval

- internal/jobs/repo/vendor_github.go
This changes the default behavior of GitHub repo auto imports to _skip_ archived repos. The prior behavior (including archived repos) can be configured by setting the `includeArchivedRepos` field to `true`.
There is currently no place in the UI where this is changeable,  so it will have to be done via direct SQL for now.
I've tested by creating an auto-import for the MergeStat org and observing that by default, no archived repos are imported. I then recreated the auto-import, except with the `includeArchivedRepos` flag set, and noted that the archived repos were imported.
Closes #1133 and #404
> feat: add `includeArchivedRepos ` auto import config flag
