mergestat/mergestat

internal/db/models.go, internal/db/queries.sql, internal/db/queries.sql.go, internal/syncer/github_repo_metadata.go, migrations/default/1647540273494_init/up.sql, schema.sql
Instead of a `JSONB` column for metadata, just list out all the columns
=> feat: refactor the `github_repo_info` table and `GITHUB_REPO_METADATA` sync type

cmd/worker/main.go, docker-compose.yaml, go.mod, go.sum
also add `stop_grace_period` to `docker-compose.yaml`
=> feat: update mergestat, add a mutex to control concurrency of GitHub API calls

internal/syncer/git_commit_stats.go, internal/syncer/git_commits.go
as an attempt to reduce memory usage on large repos
=> fix: send batched results for `GIT_COMMITS` and `GIT_COMMIT_STATS`

internal/syncer/git_commit_stats.go, internal/syncer/git_commits.go, internal/syncer/git_files.go, internal/syncer/git_refs.go
=> fix: use proper cred for git clones, uses `GITHUB_TOKEN` 

ui/src/components/RepoImage.tsx, ui/src/components/RepoSyncIcon.tsx, ui/src/views/repositories/components/repositories-table/columns.tsx, ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-name.tsx, ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-tag-list.tsx, ui/src/views/repositories/drop-downs/edit-tags-list-drop-down.tsx, ui/src/views/repositories/drop-downs/repo-data-drop-down.tsx, ui/src/views/repositories/drop-downs/sync-repos-data-drop-down/sync-data-table.tsx/columns.tsx, ui/src/views/repositories/drop-downs/sync-repos-data-drop-down/sync-data-table.tsx/row-options.tsx, ui/src/views/repositories/modals/auto-import-repository-modals/manage-auto-imports-modal.tsx, ui/src/views/repositories/repositories-view.tsx, ui/src/views/repository-data-details/components/repo-data-type-logs/index.tsx, ui/src/views/repository-data-details/components/repo-data-type-logs/logs-table/columns.tsx, ui/src/views/repository-data-details/components/repo-data-type-logs/logs-table/components/row-options.tsx, ui/src/views/repository-data-details/components/repo-data-type-logs/logs-table/components/sync-type.tsx, ui/src/views/repository-data-details/components/repo-data-type-sync-settings/settings-table.tsx, ui/src/views/repository-data-details/components/repo-data-type-sync-settings/sync-settings-form.tsx, ui/src/views/repository-data/components/sync-types-table/columns.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-data.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-now.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-status.tsx, ui/tailwind.config.js
Small spelling fix (find and replace)
=> fix: correct spelling of `samantic` to `semantic`

README.md, scripts/docker-init-entrypoint.sh, scripts/grafana/dashboards/example.json
- Update init script to also enqueue newly added syncs
- Update `README` to include more instructions for adding a `GITHUB_TOKEN`
=> fix: update default Grafana board to match latest schema

.github/workflows/publish.yaml, .gitignore
Following: https://github.com/marketplace/actions/build-and-push-docker-images
Closes #39
=> feat: first pass adding docker build + publish

CODEOWNERS
=> feat: add a `CODEOWNERS` file

cmd/worker/main.go
Match the `pool_max_conns` value to the goroutine concurrency
=> feat: set the `pool_max_conns` to match goroutine concurrency

Makefile, docker-compose.ui-dev.yaml, docker-compose.yaml, ui/.dockerignore, ui/Dockerfile, ui/next.config.js, ui/package-lock.json, ui/package.json
- Add `ui` service to `docker-compose.yaml` (and Dockerize the UI)
- Add `ui-dev` make target to start backend services in dev mode (for `ui` development)
I think this sufficiently closes #77
=> Improve `docker-compose` setup

ui/src/pages/repos/[repository]/index.tsx, ui/src/views/repositories/components/repositories-table/index.tsx, ui/src/views/repositories/repositories-view.tsx, ui/src/views/repository-data/components/sync-types-table/index.tsx
Adding near real time (Polling each 5 sec) in: 
-  **Repo List**
-  **Repo Syncs list.** 
(Complementing #69)
=> Polling data for near real time

.github/workflows/ci.yaml, Dockerfile
in CI and Docker container for the `worker`
=> chore: ugprade to go 1.18

ui/src/views/repositories/modals/add-repository-modal/index.tsx, ui/src/views/repositories/modals/add-repository-modal/modal-footer.tsx, ui/src/views/repositories/modals/add-repository-modal/modal-sidebar.tsx
Disabling bulk add repos buttons (Resolve #86).
=> fix: Disabling bulk add repos buttons

docker-compose.ui-dev.yaml, docker-compose.yaml, ui/src/__mocks__/repos.mock.ts, ui/src/__tests__/repos.test.tsx, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/state/contexts/repositories.context.tsx, ui/src/utils/constants.ts, ui/src/views/repositories/components/filter-header.tsx, ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-name.tsx, ui/src/views/repositories/hooks/useRepos.ts, ui/src/views/repositories/index.tsx
Implementing repo search filter. (Resolves #98)
- Adding `unit test` for searching `angular` repository.
=> feat(search): Implementing repo search filter

cmd/worker/main.go
- changed logic to delay the until the quota is reset
- added support for shutdown during the delay.
resolves #134
=> fix: bug with where rate limit could be depleted

ui/package-lock.json, ui/package.json, ui/src/api-logic/graphql/generated/schema.ts, ui/src/components/NavHeader/index.tsx, ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-name.tsx
Removing user icon menu. (Resolves #106)
=> fix(user-icon): Removing user icon menu for now

ui/package-lock.json, ui/package.json, ui/src/__mocks__/repo-add.mock.ts, ui/src/__mocks__/repos.mock.ts, ui/src/__tests__/repos.test.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/mutations/add-repo.ts, ui/src/components/RepoImage.tsx, ui/src/state/contexts/repositories.context.tsx, ui/src/utils/constants.ts, ui/src/views/repositories/hooks/useRepos.ts, ui/src/views/repositories/hooks/useUrlRepo.ts, ui/src/views/repositories/modals/add-repository-modal/add-repository-from-url-modal.tsx, ui/src/views/repositories/modals/add-repository-modal/index.tsx, ui/src/views/repositories/modals/add-repository-modal/modal-footer.tsx, ui/src/views/repositories/modals/add-repository-modal/modal-sidebar.tsx
Implementing adding repo functionality. (Resolves #99)
Missing things:
=> feat(add-repo): Implementing adding repo functionality

ui/src/views/repositories/components/page-header.tsx, ui/src/views/repositories/modals/add-repository-modal/add-repository-from-csv-modal.tsx, ui/src/views/repositories/modals/add-repository-modal/add-repository-from-url-modal.tsx, ui/src/views/repositories/modals/add-repository-modal/index.tsx, ui/src/views/repositories/modals/add-repository-modal/modal-footer.tsx
=> chore: update some language

ui/src/__mocks__/repo-add.mock.ts, ui/src/__mocks__/repos.mock.ts, ui/src/__tests__/repos.test.tsx, ui/src/state/contexts/repositories.context.tsx, ui/src/utils/constants.ts, ui/src/views/repositories/components/page-header.tsx, ui/src/views/repositories/hooks/useAddRepos.ts, ui/src/views/repositories/hooks/useUrlRepo.ts, ui/src/views/repositories/modals/add-repository-modal/add-repository-from-csv-modal.tsx, ui/src/views/repositories/modals/add-repository-modal/add-repository-from-url-modal.tsx, ui/src/views/repositories/modals/add-repository-modal/index.tsx, ui/src/views/repositories/modals/add-repository-modal/modal-footer.tsx
Implementing repo addition by CSV. (Resolves #100)
=> Add repo by csv

internal/db/queries.sql, internal/db/queries.sql.go, migrations/20220831164127_disable_enable_syncs.up.sql
Here we add  a boolean  column in repo_syncs and we also  add logic that handles when to sync
=> feat: adding disabled column in repo_syncs & adding bool logic

ui/package-lock.json, ui/package.json, ui/src/__mocks__/repos.mock.ts, ui/src/__mocks__/settings.mock.ts, ui/src/__tests__/settings.test.tsx, ui/src/api-logic/axios/api.ts, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/mutations/set-pat.ts, ui/src/pages/settings/index.tsx, ui/src/utils/constants.ts, ui/src/utils/index.tsx, ui/src/views/repositories/hooks/useSetPat.ts
Implementing setting PAT up functionality. (Resolves #107)
=> feat(set-pat): Implementing setting PAT up functionality

ui/src/@types.tsx, ui/src/__mocks__/imports.mock.ts, ui/src/__tests__/repos.test.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repo-imports.ts, ui/src/api-logic/mappers/imports.ts, ui/src/components/Fields/relative-time-field.tsx, ui/src/utils/constants.ts, ui/src/views/repositories/hooks/useRepoImports.ts, ui/src/views/repositories/index.tsx, ui/src/views/repositories/modals/auto-import-repository-modals/manage-auto-imports-modal.tsx, ui/src/views/repositories/modals/auto-import-repository-modals/sync-auto-import-modal.tsx
Implementing auto import list. (Resolves #104)
- Listing auto imports
- Unit testing
=> feat(auto-import-list): Implementing auto import list

ui/src/views/repository-data/components/sync-types-table/index.tsx
Just updating header labels for repo list. (Resolves #112)
=> fix(header-labels): Fixing header labels for repo list

.github/workflows/linter.yml, .sqlfluff
=> feat(linter): Adding github super linter

.github/workflows/ci-worker.yaml, .github/workflows/lint_sql.yml, .sqlfluff, .sqlfluffignore, migrations/20220511014018_init.up.sql, migrations/20220710232941_service_authentication_table.down.sql, migrations/20220710232941_service_authentication_table.up.sql, migrations/20220831142142_sync_types_descriptions.up.sql, migrations/20220902164407_trivy_scan_sync_type.up.sql, migrations/20220907164245_imported_at_publics.up.sql, migrations/20220907193542_foreign_key_missing.up.sql, migrations/20220908184342_fks_constraint_cascade.up.sql, migrations/20220913175746_enabled_to_schedule_enabled.up.sql, schema.sql
Trying out the reusable workflows
=> feat(workflows):Adding sqlfluff on workflows

internal/syncer/git_blame.go
in the newly added `GIT_BLAME` sync. This is a "hotfix" and we should address the underlying issue in the library we're using at some point.
=> fix: add a `nil` pointer check and some warn logging

ui/src/@types.tsx, ui/src/__mocks__/constants.mock.ts, ui/src/__mocks__/repos.mock.ts, ui/src/__mocks__/syncs.mock.ts, ui/src/__tests__/syncs.test.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repo-syncs.query.ts, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/state/contexts/repositories.context.tsx, ui/src/utils/constants.ts, ui/src/views/repositories/drop-downs/repo-additional-actions-drop-down.tsx, ui/src/views/repositories/modals/remove-repository-modal/index.tsx, ui/src/views/repository-data/components/repo-settings.tsx, ui/src/views/repository-data/index.tsx
Implementing remove repo from settings tab. (Resolves #110)
- Unit Testing to remove a repo
=> feat(remove-repo-settings): Implementing remove repo from settings tab

ui/src/pages/settings/index.tsx, ui/src/views/repositories/components/page-header.tsx, ui/src/views/repositories/modals/auto-import-repository-modals/manage-auto-imports-modal.tsx, ui/src/views/repositories/modals/auto-import-repository-modals/sync-auto-import-modal.tsx
=> Various help text additions/modifications in the UI

ui/src/__mocks__/constants.mock.ts, ui/src/__mocks__/repos.mock.ts, ui/src/__tests__/repos.test.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/views/repositories/index.tsx
Fixing bug to show No data available! when there's no repos found. (Resolves #259)
=> Bug empty data

migrations/20220907164245_imported_at_publics.up.sql
=> chore(migrations): fixing error introduced by sqlfluff

Dockerfile
Please @patrickdevivo  @amenowanna   test this on your local env :)
=> feat(dockerfile): Added  cache option when building image

ui/src/api-logic/graphql/queries/get-repos.query.ts
=> feat: add `REPO_DESC` to default order on `/repos` page

internal/scheduler/scheduler.go
to drive the job retention period
=> feat: use a `REPO_SYNC_QUEUE_RETENTION_DAYS` env

ui/src/views/repositories/modals/auto-import-repository-modals/manage-auto-imports-modal.tsx
just to consistent - repos can be auto _imported_ and sync types _sync_ data to the db
Closes #225
=> fix: tiny wording change

ui/src/pages/authentication/index.tsx
=> feat: some updates to the login language

cmd/worker/main.go, migrations/20220922202459_cascade_repos_fk.up.sql
Reference :) https://github.com/mergestat/fuse/issues/311
=> feat(migrations): CASCADE for all repos when import is deleted

ui/src/@types.tsx, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/utils/index.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-status.tsx, ui/src/views/repository-data/components/sync-types-table/index.tsx
Adjusting logic for time bars. (Resolves #117)
=> fix(time-bars): Adjusting logic for time bars

cmd/worker/main.go, internal/db/models.go, internal/db/queries.sql, internal/db/queries.sql.go
Direct link to the issue https://github.com/mergestat/fuse/issues/318 :)
=> feat(worker): Update enqueue system to not starve low prio queues

internal/db/queries.sql, internal/db/queries.sql.go
See https://github.com/mergestat/fuse/issues/277 for full context
Closes #277
=> fix: address bug described by #277

migrations/20220927013137_git_commit_stats_file_modes.up.sql
PK is now allowed to have null values so we need to set a default value for the new columns and set them to NOT NULL
=> fix: adding default value and NOT NULL

docker-compose.yaml
=> Add `shipyard.build` setup to begin deploying on every

internal/syncer/syncer.go
=> feat: add log lines for every `git clone` operation

ui/src/views/repositories/components/repositories-table/index.tsx, ui/src/views/repositories/index.tsx
in the `/repos` table.
Closes #212
=> feat: remove bulk actions UI elements

ui/src/api-logic/mappers/repo-syncs.ts, ui/src/components/Fields/relative-time-field.tsx, ui/src/utils/index.tsx, ui/src/views/repository-data/components/sync-types-table/index.tsx
- `N/A` -> `-` in some spots
- use milliseconds in seconds for higher precision
Closes #216
=> feat: fix up some of the relative time handling

ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/api-logic/mappers/repos.ts
for displaying "Last Sync" in the UI
Closes #215
=> fix: use `doneAt` instead of `startedAt`

ui/src/api-logic/mappers/syncs-logs.ts, ui/src/utils/constants.ts, ui/src/views/repository-data-details/components/repo-data-type-logs/logs-table/columns.tsx, ui/src/views/repository-data-details/components/repo-data-type-logs/logs-table/index.tsx, ui/src/views/repository-data-logs-details/index.tsx
Closes #124
Makes some initial/empty states look better.
=> feat: various tweaks to log entries styling

ui/src/@types.tsx, ui/src/__mocks__/syncs.mock.ts, ui/src/__tests__/syncs.test.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repo-syncs.query.ts, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/api-logic/graphql/queries/get-sync-history-logs.query.ts, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/api-logic/mappers/repos.ts, ui/src/api-logic/mappers/syncs-logs.ts, ui/src/components/RepoSyncIcon.tsx, ui/src/pages/repos/[repository]/[syncTypeId]/[logID].tsx, ui/src/pages/repos/[repository]/[syncTypeId]/index.tsx, ui/src/utils/constants.ts, ui/src/utils/index.tsx, ui/src/views/hooks/useRepos.ts, ui/src/views/hooks/useSyncs.ts, ui/src/views/repositories/drop-downs/repo-data-drop-down.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-status.tsx
Showing syncs error icons. (Resolves #240)
- I commented some checks in 2 tests meanwhile cuz they were no working.
=> fix(error-syncs): showing syncs error icons

ui/src/views/repositories/components/filter-header.tsx
=> chore: comment out the `TagsListDropDown`

ui/src/components/NavHeader/index.tsx, ui/src/styles/globals.css
- Added `Avatar` and `t-nav-item` styles to user menu
- Moved log out action in dropdown
=> Update user menu

ui/src/pages/settings/repo-auto-imports/[importId].tsx, ui/src/styles/globals.css, ui/src/views/repositories/modals/add-repository-modal/auto-import-from-git-modal.tsx, ui/src/views/settings/index.tsx, ui/src/views/settings/repo-auto-imports/index.tsx
- fix: for t-table-clickable the header should not be interactive
- fix: address react key conflict error
- feat: make the default sync types for repo auto imports clickable
- fix: use the <Link> component in the /settings sidebar nav
=> feat: some small UI fixes

migrations/20221010082656_fix_pr_reviews_pk.up.sql
=> fix: add repo_id to github_pull_request_reviews_pkey

ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/auth.ts, ui/src/layouts/SidebarLayout.tsx, ui/src/pages/connect/index.tsx
Getting connection data from database. (Resolves #357)
**Note:** I will avoid to keep implementing unit testing due application is a little changeable for now. I understand we are gonna focus more in unit testing for v2 any way.
=> feat(connect-data): Getting connection data

ui/src/@types.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/mutations/syncs.ts, ui/src/api-logic/graphql/queries/get-repo-syncs.query.ts, ui/src/api-logic/graphql/queries/get-sync-history-logs.query.ts, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/api-logic/mappers/syncs-logs.ts, ui/src/pages/repos/[repository]/[syncTypeId]/index.tsx, ui/src/views/hooks/useSyncNow.ts, ui/src/views/hooks/useSyncsLogs.ts, ui/src/views/repository-data-details/components/repo-data-type-sync-settings/sync-settings-form.tsx, ui/src/views/repository-data-details/index.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-status.tsx, ui/src/views/repository-data/components/sync-types-table/index.tsx
Adding schedule functionality. (Resolves #194)
- No Unit Testing
=> feat(schedule): Adding schedule functionality

cmd/worker/main.go, docker-compose.ui-dev.yaml, docker-compose.yaml, graphql/service-credentials/index.js, graphql/service-credentials/index.ts, internal/syncer/syncer.go
to remove `fuse` from the name.
=> fix: rename `FUSE_SECRET` env to `ENCRYPTION_SECRET`

ui/src/views/sql-query-editor/components/state-filled.tsx
Just a quick fix for CSV exporting functionality.
=> chore(sql-query): Fixing exporting CSV format

ui/src/pages/settings/repo-auto-imports/[importId].tsx
in handling repo auto imports (in the `/settings` area).
Closes #425
=> fix: account for `undefined` `defaultSyncTypes`

ui/src/@types.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/api-logic/mappers/repos.ts, ui/src/views/repositories/components/filter-header.tsx, ui/src/views/repositories/components/repositories-table/index.tsx, ui/src/views/repositories/index.tsx
- Started adding top metrics
- I was able to figure out the `Number of repos` and `Avg number of syncs`, but not `Avg sync time` for which I could use some help
(Resolves #222)
=> feat: add metrics to repo overview

ui/src/views/sql-query-editor/index.tsx
Fixing loading state in query editor. (Resolves #420)
=> Initial query state

ui/src/styles/globals.css, ui/src/views/sql-query-editor/components/state-empty.tsx, ui/src/views/sql-query-editor/index.tsx
Adjusting message for executions without results. (Resolves #422)
=> chore(query-editor): Adjusting message for executions without results

ui/src/views/repository-data/index.tsx
Redirecting to repos when given id does not exist. (Resolves #378)
=> chore(repos): Redirecting to repos when given id does not exist

.github/workflows/ci-worker.yaml, internal/helper/helper_test.go, internal/helper/sql_conversions_test.go
Instead of a `bool`, use `func` that can be supplied to perform any error specific checks (is the error an "expected" error of a particular type?)
=> feat: tweak how errors are checked for in the test cases

ui/src/pages/settings/index.tsx, ui/src/views/hooks/useImports.ts, ui/src/views/repositories/modals/add-repository-modal/add-repository-from-url-modal.tsx, ui/src/views/repositories/modals/add-repository-modal/auto-import-from-git-modal.tsx
Adding enter key actions. (Resolves #192)
=> chore(enter-key): Adding enter key actions

ui/src/api-logic/mappers/repos.ts
Showing last sync in repo list. (Resolves #431)
=> chore(repos): Showing last sync in repo list

internal/warehouse/github_actions.go
filter from workflow runs should be removed until later iterations
=> fix(warehouse): removing created filter from actions

ui/src/views/sql-query-editor/index.tsx
Fixing error state in query editor. (Resolves #490)
=> chore(query-editor): Fixing error state

ui/src/@types.tsx, ui/src/__mocks__/repos.mock.ts, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/api-logic/mappers/repos.ts, ui/src/pages/repos/[repository]/index.tsx, ui/src/utils/constants.ts, ui/src/views/hooks/useAddRepos.ts, ui/src/views/hooks/useImports.ts, ui/src/views/hooks/useMetrics.ts, ui/src/views/hooks/useRepoImports.ts, ui/src/views/hooks/useRepos.ts, ui/src/views/hooks/useSyncNow.ts, ui/src/views/hooks/useSyncs.ts, ui/src/views/hooks/useSyncsLogs.ts, ui/src/views/repositories/index.tsx, ui/src/views/repositories/modals/remove-import-modal/index.tsx, ui/src/views/repositories/modals/remove-repository-modal/index.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-now.tsx, ui/src/views/repository-data/components/sync-types-table/index.tsx, ui/src/views/settings/repo-auto-imports/index.tsx
Splitting metric queries. (Resolves #485)
=> chore(metrics): Splitting metric queries

Makefile, docker-compose.yaml, docs/README.md
and add `make` targets for easier building and a note to `docs/README.md`
=> feat: clean up `docker-compose` a bit

docker-compose.yaml
Version tag will follow after merge
=> chore bump Docker image versions to `1.2.1-beta`

ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/auth.ts, ui/src/pages/settings/index.tsx, ui/src/views/hooks/useSetPat.ts
Adding setted token indicator. (Resolves #342)
=> feat(pat): Adding setted token indicator

go.mod, go.sum, internal/warehouse/batch_logs.go, internal/warehouse/github_actions.go
Adding Batch Logs to actions sync .This way users are aware of what is happening meanwhile they wait :) 
resolves #459
=> add some log messages to the GitHub Actions sync

ui/src/api-logic/mappers/syncs-logs.ts
Fixing date for queued syncs. (Resolves #455)
=> fix(queued-syncs): Fixing date for queued syncs

ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/mutations/syncs.ts, ui/src/views/repository-data/components/sync-types-table/index.tsx
Fixing schedule toggle. (Resolves #478)
=> fix(schedule): Fixing schedule toggle

ui/package-lock.json, ui/package.json, ui/src/views/repositories/components/filter-header.tsx, ui/src/views/sql-query-editor/components/state-filled.tsx
Fixing border pagination buttons. (Resolves #476)
=> chore(tables): Fixing border pagination buttons

ui/src/utils/index.tsx, ui/src/views/repository-data-details/components/repo-data-type-logs/logs-table/index.tsx, ui/src/views/repository-data-logs-details/index.tsx
Implementing copy to clipboard for logs. (Resolves #479)
=> feat(logs): Implementing copy to clipboard for logs

internal/warehouse/github_actions.go
We were not upserting the jobs information when a log call failed .
Now with this change we are upserting the job without the log .
To test this go for  a run the actions sync a repo , wait until the if gets a warning level error from the logs call , check the ID of that job , go to the DB and search for that ID  and  if that job exits this is  correct 
`SELECT * from  github_actions_workflow_run_jobs where ID=jobid`
=> fix(actions):Upserting jobs information despite log call error

Dockerfile, go.mod
Closes #449 and #447 concurrently
=> chore: update to go 1.19

go.mod, go.sum
This reverts commit e3776c84ac50c4e49ccd3f7d6dd6f9edb354097f.
=> Revert "fix(deps): update go.riyazali.net/sqlite digest to bd9e30b"

docker-compose.yaml
=> chore: bump versions in `docker-compose` file

migrations/900000000000005_fix_admin_role.up.sql, scripts/validate-users.sql
=> fix: admin role permissions

docker-compose.yaml
=> Bump version 1.3.1 beta

migrations/900000000000008_fix_set_role.up.sql, scripts/validate-users.sql
User management tests updated.
resolves #557
=> fix: user_mgmt_set_user_role to remove createrole

ui/src/@types.tsx, ui/src/__mocks__/constants.mock.ts, ui/src/__mocks__/syncs.mock.ts, ui/src/__mocks__/users.mock.ts, ui/src/__tests__/users.tes.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/users.ts, ui/src/api-logic/mappers/users.ts, ui/src/utils/constants.ts, ui/src/views/settings/user-management/index.tsx
Implementing user list functionality.
- User list
- Searching input
- Unit Testing
=> feat(users): Implementing user list functionality

CONTRIBUTING.md, README.md
=> feat(contributing): add a contributing.md

go.sum
=> chore: run `go mod tidy`

ui/src/__mocks__/constants.mock.ts, ui/src/__mocks__/users.mock.ts, ui/src/__tests__/users.tes.tsx, ui/src/utils/constants.ts, ui/src/views/settings/modals/change-password-modal/index.tsx, ui/src/views/settings/user-settings/index.tsx
Implementing change password in settings.
- Unit testing
=> chore(users): Implementing change password in settings

ui/src/views/settings/modals/add-user-modal/index.tsx, ui/src/views/settings/modals/change-password-modal/index.tsx, ui/src/views/settings/modals/edit-user-modal/index.tsx
Adjusting modal buttons to be disabled when form is no ready
=> chore(users): Adjusting modal buttons.

ui/lib/apollo.ts
Going to login when token is removed from cookie. (Resolves #599)
=> fix(session): Going to login when token is removed from cookie

examples/git/dependencies/sbom/syft/sql/most-common-artifacts.sql, examples/git/dependencies/sbom/syft/sql/most-common-go-module-artifacts.sql, examples/git/dependencies/sbom/syft/sql/repos-with-go-module-artifact.sql
- `most-common-artifacts.sql`
- `most-common-go-module-artifacts.sql`
- `repos-with-go-module-artifact.sql`
=> feat(examples): add a couple more SBOM (syft) examples

ui/package-lock.json, ui/package.json
=> chore(new-release): Updating blocks version.

graphql/exec-sql/index.js, graphql/exec-sql/index.ts, ui/package-lock.json, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/api-logic/graphql/queries/sql-queries.ts, ui/src/utils/index.tsx, ui/src/views/hooks/useMetrics.ts, ui/src/views/sql-query-editor/components/state-filled.tsx, ui/src/views/sql-query-editor/index.tsx
Use `rowMode: 'array'` approach, which closes #423 (see for more context). This approach should allow us to return results with columns that have the same name.
=> feat: refactor the `execSQL` implementation

ui/src/@types.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/mutations/syncs.ts, ui/src/api-logic/graphql/queries/get-repo-syncs.query.ts, ui/src/api-logic/graphql/queries/get-sync-history-logs.query.ts, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/api-logic/mappers/syncs-logs.ts, ui/src/pages/repos/[repository]/[syncTypeId]/index.tsx, ui/src/views/hooks/useSyncNow.ts, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-now.tsx, ui/src/views/repository-data/components/sync-types-table/index.tsx
Setting `typeGroup` when syncing. (Resolves #633)
=> feat(sync): Setting typeGroup when syncing

ui/package-lock.json, ui/package.json
addresses many of the PRs opened by Renovate, at one time
=> chore: updates some UI dependencies

ui/src/views/repository-data-details/index.tsx, ui/src/views/repository-data-logs-details/index.tsx, ui/src/views/repository-data/components/page-header.tsx
=> fix: update the external link to the GitHub repo (not just the owner) in the breadcrumb

docker-compose.yaml
Part of https://github.com/mergestat/mergestat/issues/635
=> chore: add note about adding a `volumes` block for local repos

ui/src/views/repositories/components/empty-repository.tsx
=> fix: remove extraneous button for clarity

ui/src/views/settings/repo-auto-imports/index.tsx
with a better message. Also add a link/CTA
Closes #983
=> fix: replace `No data available!`

ui/src/views/repositories/components/empty-repository-table.tsx
card, when no auth token is setup
Closes #683
=> feat: add link to docs in the `GitHub Authentication Token`

ui/src/@types.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repo-syncs.query.ts, ui/src/api-logic/graphql/queries/get-repos.query.ts, ui/src/api-logic/graphql/queries/get-sync-history-logs.query.ts, ui/src/api-logic/mappers/repos.ts, ui/src/components/RepoSyncIcon.tsx, ui/src/utils/constants.ts, ui/src/utils/index.tsx, ui/src/views/repositories/components/repositories-table/index.tsx, ui/src/views/repositories/drop-downs/repo-data-drop-down.tsx, ui/src/views/repository-data/components/sync-types-table/components/repository-sync-status.tsx, ui/src/views/sql-query-editor/components/state-filled.tsx
Implementing sync warnings experience. (Resolves #457)
=> feat(sync-warnings): Implementing sync warnings experience

ui/src/layouts/SidebarLayout.tsx, ui/src/pages/connect/index.tsx, ui/src/views/hooks/useCurrentUser.ts, ui/src/views/settings/user-management/index.tsx, ui/src/views/settings/user-settings/index.tsx
Showing current username in connect page. (Resolves #612)
=> fix(connect): Showing current username in connect page

Dockerfile, internal/syncer/gosec_repo_scan.go, internal/syncer/syncer.go, migrations/900000000000018_add_gosec_sync.up.sql
This PR adds a new sync type for the `gosec` tool. Closes #676
=> feat(syncer): add new sync type for gosec

ui/src/views/repositories/components/repositories-table/index.tsx
=> fix: spacing issue in repos table. Closes #715

docker-compose.yaml
Oops, fat-fingered in previous PR
=> fix: correct version

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.9.0-beta...main
=> chore: bump to `v1.10.0-beta`

docker-compose.yaml
=> fix: typo in the `docker-compose` file, `::` -> `:`

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.10.0-beta...main
=> chore: bump to `1.11.0-beta`

go.mod, go.sum
Reverts mergestat/mergestat#754
=> Revert "fix(deps): update github.com/mergestat/sqlq digest to 1655674"

ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/sql-queries.ts, ui/src/views/sql-query-editor/index.tsx
=> feat: start tracking query history from SQL run from the UI

.sqlfluff, Dockerfile, internal/syncer/grype_repo_scan.go, internal/syncer/syncer.go, migrations/900000000000023_grype_repo_scan.up.sql
This pr addresses  the new grype sync type
Closes #712 
to test this :
1. Create a new org/user import
2. And select the default sync  grype repo scan :)
=> feat(syncer): Adding grype scanner sync

cmd/worker/main.go, go.mod, go.sum
See here: https://go.dev/doc/database/manage-connections
=> fix: call `SetMaxOpenConns` with the same number used in the `pgxpool` setup

internal/db/models.go, migrations/900000000000026_saved_queries.up.sql
=> fix: typo in table comments breaking `sqlc generate`

go.mod, go.sum
=> feat(sqlq):Upgrade sqlq library

ui/package-lock.json, ui/package.json, ui/src/@types.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-schema.ts, ui/src/api-logic/mappers/schema.ts, ui/src/views/sql-query-editor/components/schema-section.tsx, ui/src/views/sql-query-editor/components/sql-editor-section.tsx
Implementing schema info for query editor. (Resolves #521)
=> chore(schema): Implementing schema info for query editor

ui/src/views/repositories/modals/remove-import-modal/index.tsx
Loom video
https://www.loom.com/share/b2fa89fa13ac4ff0b9d4ad5afb804056
Closes https://github.com/mergestat/mergestat/issues/590
=> fix: Add loading state for removing a repo auto import

ui/src/views/sql-query-editor/tabs/tab-table.tsx
Loom video
https://www.loom.com/share/fabf36506285470ea4e3e219afa1c60f
Closes https://github.com/mergestat/mergestat/issues/708
=> fix: `Copy` button no longer works on `Queries` page

ui/src/views/repository-data-details/components/repo-data-type-sync-settings/sync-settings-form.tsx
Loom video
https://www.loom.com/share/55ab855731b24406886f56c030cb23f6
Closes https://github.com/mergestat/mergestat/issues/811
=> feat: Add user feedback when the repo sync schedule toggle is used/modified

ui/src/views/repositories/modals/add-repository-modal/add-repository-from-url-modal.tsx, ui/src/views/repositories/modals/add-repository-modal/auto-import-from-git-modal.tsx
Closes #852 
Disabling the buttons when the input is equal to empty string
=> fix(importer): Disabling button whe no input is given

ui/src/components/Sidebar/index.tsx
=> fix: only highlight one item in the navbar at a time

internal/db/models.go, internal/db/queries.sql, internal/db/queries.sql.go, internal/jobs/repo/import.go
=> fix(repo): Showing tags in the UI

ui/src/views/hooks/useAddRepos.ts
=> fix(hooks): Waiting for state to change to continue op

go.mod, go.sum, internal/db/models.go, internal/db/queries.sql, internal/db/queries.sql.go, internal/helper/helper.go, internal/helper/helper_test.go, internal/jobs/repo/import.go, internal/mocks/mock_actions.go, internal/syncer/github_repo_metadata.go, internal/warehouse/github_actions.go, internal/warehouse/github_actions_test.go, internal/warehouse/warehouse.go, migrations/900000000000032_repo_stats_tables.up.sql
This  content changes the Graphql approach to a Rest API  in the need of  security properties
To test just import any ORG/USER and sync the github  repo metada sync with credentials equal or above admin
Closes #846
=> feat(syncer):  Adding new security columns

ui/package-lock.json, ui/package.json, ui/src/views/sql-query-editor/tabs/tab-table.tsx
Loom video
https://www.loom.com/share/5812043826f2454f89d6d0ce8b6ec8b7
Closes https://github.com/mergestat/mergestat/issues/753
=> feat: Use the BlueprintJS table component (spreadsheet like experience) for query results

ui/src/state/contexts/query.context.tsx, ui/src/views/repo-git-sources/add-source/index.tsx, ui/src/views/repo-git-sources/git-source-detail/components/auth/github.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/components/manual-import-table.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/tabs/repos-auto.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/tabs/repos-manual.tsx, ui/src/views/repo-git-sources/git-source-detail/components/stats.tsx, ui/src/views/repo-git-sources/git-source-detail/modals/add-repo-import.tsx, ui/src/views/repo-git-sources/git-source-detail/modals/remove-auth-credential.tsx, ui/src/views/repositories/components/repositories-table/index.tsx
some other small fixes here and there as well.
=> fix: various wording tweaks to the `Git Sources` work

cmd/worker/main.go, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/mutations/auth-credentials.ts
in order to fix private repos access.
This does _not_ appear to resolve GitHub API syncs that use a GitHub token however. @riyaz-ali @german-mergestat
=> fix: set a dummy username when setting the GitHub token

ui/src/views/repo-git-sources/git-source-detail/components/repos/tabs/repos-manual.tsx
Adjusting label for Generic Git sources flow.
=> chore(refactor): Adjusting label for Generic Git sources flow.

internal/syncer/git_blame.go
Changing git blame to store the blame objects into a json file
Closes #871
=> feat(syncer): Changing the pattern to store objects in a file

ui/src/api-logic/graphql/queries/get-saved-query.ts, ui/src/views/saved-queries/index.tsx, ui/src/views/sql-query-editor/index.tsx
=> chore(saved-queries): Adding loading and order desc

graphql/exec-sql/index.js, graphql/exec-sql/index.ts, ui/src/views/sql-query-editor/tabs/tab-table.tsx
also update the pagination values in the query results table experience.
Closes #872
=> feat: bump query row limit to `5000` and default to `1000`

internal/syncer/git_commit_stats.go
To test this piece check counts between main and this branch
Closes #909
=> feat(syncer): buffer commit stats in a json file before db insert

internal/jobs/repo/vendor_bitbucket.go, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/mutations/auth-credentials.ts, ui/src/api-logic/graphql/queries/get-repos.ts, ui/src/api-logic/mappers/imports.ts, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/api-logic/mappers/repos.ts, ui/src/components/RepoImage.tsx, ui/src/utils/constants.ts, ui/src/utils/index.tsx, ui/src/views/hooks/useCredentials.ts, ui/src/views/hooks/useRepos.ts, ui/src/views/hooks/useSetPat.ts, ui/src/views/repo-git-sources/add-source/index.tsx, ui/src/views/repo-git-sources/git-source-detail/components/auth/bitbucket.tsx, ui/src/views/repo-git-sources/git-source-detail/components/auth/github.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/tabs/repos-auto.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/tabs/repos-manual.tsx, ui/src/views/repo-git-sources/git-source-detail/modals/add-repo-import.tsx, ui/src/views/repositories/components/repositories-table/repositories-table-columns/repository-name.tsx, ui/src/views/repositories/index.tsx
Implementing a first approach for `Bitbucket` flow. (Resolves #893)
=> chore(refactor): First approach for Bitbucket Git Source flow.

internal/syncer/git_commits.go
To test this please check the counts in this branch vs main branch :).Also make sure that all fields are populated as expected
Closes #921
=> feat(syncer): buffer commits into a file before inserting to DB

ui/src/utils/index.tsx
=> fix(ui): Fixing time differences function

internal/jobs/repo/vendor_gitlab.go
For now, the "canonical" format for a GitLab repo will be `https://gitlab.com/owner/repo`, to match what we do for GitHub
=> fix: addresses some repo URL formatting in GitLab auto importing

internal/syncer/git_blame.go, internal/syncer/git_commit_stats.go, internal/syncer/git_commits.go, internal/syncer/git_files.go, internal/syncer/git_refs.go, internal/syncer/gitleaks_repo_scan.go, internal/syncer/gosec_repo_scan.go, internal/syncer/syft_repo_scan.go, internal/syncer/yelp_detect_secrets_repo_scan.go, internal/warehouse/github_actions.go
=> chore(helper): Change tmp dir pattern creation

internal/jobs/repo/vendor_gitlab.go, ui/src/@types.tsx, ui/src/api-logic/axios/api.ts, ui/src/api-logic/mappers/imports.ts, ui/src/api-logic/mappers/repo-syncs.ts, ui/src/api-logic/mappers/repos.ts, ui/src/api-logic/mappers/syncs-logs.ts, ui/src/utils/constants.ts, ui/src/utils/index.tsx, ui/src/views/hooks/useRepos.ts, ui/src/views/hooks/useSetPat.ts, ui/src/views/repo-git-sources/add-source/index.tsx, ui/src/views/repo-git-sources/git-source-detail/components/auth/git-hub-lab.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/tabs/repos-auto.tsx, ui/src/views/repo-git-sources/git-source-detail/modals/add-repo-import.tsx, ui/src/views/repo-git-sources/git-source-detail/tabs/overview.tsx, ui/src/views/repository-data-details/index.tsx, ui/src/views/repository-data-logs-details/index.tsx, ui/src/views/repository-data/components/page-header.tsx, ui/src/views/repository-data/index.tsx
Adding first approach for `GitLab` flow.
=> chore(gitlab): Adding GitLab flow

ui/src/api-logic/graphql/queries/get-repos.ts
=> feat(graphql): only counting syncs that have scheduleEnabled true

ui/src/api-logic/mappers/charts/apex-chart.ts
=> fix(ui): Checking for nulls in axis creations

docker-compose.ui-dev.yaml, graphql/Dockerfile, graphql/container-sync-jobs/index.js, graphql/container-sync-jobs/index.ts, graphql/container-sync-jobs/package-lock.json, graphql/container-sync-jobs/package.json, graphql/container-sync-jobs/tsconfig.json
This PR adds support for 'sync now' runs in the new container-based sync model. 
See: #947
=> feat: add support for 'sync now' jobs

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.22.1-beta...main
=> chore: bump version to `1.22.2-beta`

ui/src/@types.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/get-repo-imports.ts, ui/src/api-logic/mappers/git-sources/imports.ts, ui/src/views/repo-git-sources/git-source-detail/components/repos/components/auto-import-table.tsx
Adding tooltip when auto import fails. (Resolves #936)
=> feat(auto-import) Adding tooltip when auto import fails.

internal/syncer/git_commit_stats.go
Reverts mergestat/mergestat#910
@amenowanna validated this addresses the missing commit stats/weirdness we discovered
=> Revert "feat(syncer): buffer commit stats in a json file before db insert"

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.22.3-beta...main
=> chore: bump to `1.22.4-beta`

ui/src/styles/globals.css, ui/src/views/repo-data-container/repository-data-details/components/logs-table/index.tsx, ui/src/views/repo-data-container/repository-data-details/components/sync-settings/index.tsx, ui/src/views/repo-data-container/repository-data-details/index.tsx, ui/src/views/repo-data-container/repository-data/components/page-header.tsx, ui/src/views/repo-data-container/repository-data/components/sync-types-table/components/repository-sync-now.tsx, ui/src/views/repo-data-container/repository-data/components/sync-types-table/components/repository-sync-type-description.tsx, ui/src/views/repo-data-container/repository-data/tabs/repo-syncs.tsx, ui/src/views/repo-git-sources/add-source/index.tsx, ui/src/views/repo-git-sources/git-source-detail/components/auth/bitbucket.tsx, ui/src/views/repo-git-sources/git-source-detail/components/auth/git-hub-lab.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/components/auto-import-table.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/components/manual-import-table.tsx, ui/src/views/repo-git-sources/git-source-detail/components/repos/index.tsx, ui/src/views/repo-git-sources/git-source-detail/index.tsx, ui/src/views/repo-git-sources/git-sources/components/git-sources-table.tsx, ui/src/views/repo-sync-detail/components/git-sources-table.tsx, ui/src/views/repo-sync-detail/components/git-sources.tsx, ui/src/views/repo-sync-detail/components/settings.tsx, ui/src/views/repo-sync-detail/index.tsx, ui/src/views/repo-sync-detail/modals/enable-all-repos.tsx, ui/src/views/repo-syncs/components/add-container-sync.tsx, ui/src/views/repo-syncs/components/container-syncs-table.tsx, ui/src/views/saved-queries/components/saved-queries-table.tsx, ui/src/views/shared/filter-header.tsx, ui/src/views/shared/no-data-found.tsx, ui/src/views/sql-query-editor/components/sql-editor-section.tsx, ui/src/views/sql-query-editor/modals/query-history.tsx
- General spacing and alignment fixes
- Made saved queries table more consistent with rest of UI
- Fixed scroll on `repo sync detail`, `repo detail (container)`, `git source detail`
- Added links to `ListItems` to detail views
- Consistent panel titles
- Removed borders from tabs
**Screens**:
=> UI improvements

internal/syncer/git_blame.go, internal/syncer/git_commit_stats.go, internal/syncer/git_commits.go, internal/syncer/git_files.go, internal/syncer/git_refs.go, internal/syncer/gitleaks_repo_scan.go, internal/syncer/gosec_repo_scan.go, internal/syncer/grype_repo_scan.go, internal/syncer/syft_repo_scan.go, internal/syncer/yelp_detect_secrets_repo_scan.go, internal/warehouse/github_actions.go
=> feat: encode the `repo-id` in the tmp dir path when cloning

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.22.4-beta...main
=> chore: bump version to `1.22.5-beta`

migrations/900000000000053_add_repos_stats_functions.up.sql
Adding function for stats in the UI 
relates to #986
=> feat(migrations): adding functions for UI stats

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v1.22.5-beta...main
=> chore: bump to `1.22.6-beta`

README.md, docker-compose.yaml, ui/README.md
since we haven't been investing in it, and our approach has changed a bit since. Hopefully should avoid some confusion.
=> chore: comment out `grafana` for now

ui/src/views/repo-sync-detail/modals/enable-all-repos.tsx
Fixing hardcoded total repos enabling syncs on the modal.
=> fix(syncs-modal) Fixing hardcoded total repos on enabling syncs modal.

ui/src/api-logic/mappers/charts/recharts.ts, ui/src/views/repo-explorer/components/barchart-horizontal.tsx, ui/src/views/repo-explorer/components/barchart-vertical.tsx, ui/src/views/repo-explorer/components/cards-stats-explore.tsx, ui/src/views/repo-explorer/components/custom-top-repos.tsx, ui/src/views/repo-explorer/components/header-explore.tsx
Addressing some comments for repo explore page. ([Notes](https://www.notion.so/mergestat/Repo-Explore-Notes-d271a81b841c44d085cc3741264b05ea))
=> chore(repo-explore) Addressing some comments for repo explore page.

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v2.0.0-beta...main
=> chore: bump to `2.1.0-beta`

ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/graphql/queries/sql-queries.ts, ui/src/state/contexts/query.context.tsx, ui/src/views/hooks/useQueryEditor.ts, ui/src/views/hooks/useTabs.tsx, ui/src/views/sql-query-editor/components/state-filled.tsx, ui/src/views/sql-query-editor/index.tsx, ui/src/views/sql-query-editor/tabs/tab-table.tsx
Adjusting new rows limit design in query page. (Resolves #924)
=> fix(query-page) Adjusting new rows limit design in query page.

ui/src/views/sql-query-editor/tabs/tab-table.tsx
Solving query table result issue. (Resolves #1055)
=> fix(query-editor) Solving query table result issue.

ui/src/styles/globals.css, ui/src/views/repo-explorer/components/barchart-horizontal.tsx, ui/src/views/repo-explorer/components/barchart-vertical.tsx, ui/src/views/repo-explorer/components/cards-stats-explore.tsx, ui/src/views/repo-explorer/components/custom-top-repos.tsx, ui/src/views/repo-explorer/components/header-explore.tsx, ui/src/views/repo-explorer/components/stats-explore.tsx, ui/src/views/repo-explorer/components/time-grain-dropdown.tsx
=> fix: small styling improvements to explore ui

internal/jobs/repo/vendor_bitbucket.go, internal/jobs/repo/vendor_github.go, internal/jobs/repo/vendor_gitlab.go
=> fix(#1088): check if defualt container syncs are also configured

migrations/900000000000067_add_queries_only_role.up.sql, ui/src/@types.tsx, ui/src/__tests__/users.test.tsx, ui/src/api-logic/graphql/generated/schema.ts, ui/src/api-logic/mappers/users.ts, ui/src/utils/constants.ts, ui/src/utils/index.tsx
=> feat: add queries only role

docker-compose.yaml
https://github.com/mergestat/mergestat/compare/v2.2.1-beta...main
=> chore: release `2.3.0-beta`
